healthcare/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('appointment/', views.appointment, name="appointment"),
    path('contact/', views.contact, name="contact"),
    path('gallery/', views.gallery, name="gallery"),

]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home/index.html')


def about(request):
    return render(request, 'home/about.html')


def appointment(request):
    return render(request, 'home/appointment.html')


def contact(request):
    return render(request, 'home/contact.html')


def gallery(request):
    return render(request, 'home/gallery.html')

home/templates/home/about.html
{% extends 'home/home.html'%}
{% load static %}
{% block change%}
	<!-- banner 2 -->
	<div class="inner-banner-w3ls">
		<div class="container">

		</div>
		<!-- //banner 2 -->
	</div>
	<!-- page details -->
	<div class="breadcrumb-agile">
		<div aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="{% url 'home:index'%}">Home</a>
				</li>
				<li class="breadcrumb-item active" aria-current="page">About Us</li>
			</ol>
		</div>
	</div>
	<!-- //page details -->
{% endblock %}
{% block body %}
	<!-- about -->
	<section class="about py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="w3ls-titles text-center mb-md-5 mb-4">
				<h3 class="title">About Us</h3>
				<span>
					<i class="fas fa-user-md"></i>
				</span>
			</div>
			<p class="aboutpara text-center mx-auto">Maecenas ac euismod eros. Aliquam a suscipit nibh. Aliquam iaculis erat
				porta mauris fermentum lacinia. Donec posuere
				a massa sit amet sagittis. Nam ut nulla a ligula dictum imperdiet nec ut mauris. Etiam ipsum ipsum, ultrices id
				nisi
				ac, pretium efficitur ex. Vestibulum a maximus magna, sit amet ultrices nisi. In laoreet placerat turpis.</p>

			<div class="row about_grids mt-5">
				<div class="col-lg-4">
					<img src='{% static "home/images/blog1.jpg" %}' alt="" class="img-fluid" />
					<h3 class="mt-3 text-dark">Aliquam iaculis erat porta </h3>
					<p class="my-3">Nam ut nulla a ligula dictum imperdiet nec ligula dictum imperdiet nec</p>
					<a href="single.html">Read More</a>
				</div>
				<div class="col-lg-4 my-lg-0 my-5">
					<img src='{% static "home/images/blog2.jpg" %}' alt="" class="img-fluid" />
					<h3 class="mt-3 text-dark">Aliquam iaculis erat porta </h3>
					<p class="my-3">Nam ut nulla a ligula dictum imperdiet nec ligula dictum imperdiet nec</p>
					<a href="single.html">Read More</a>
				</div>
				<div class="col-lg-4">
					<img src='{% static "home/images/blog3.jpg"%}' alt="" class="img-fluid" />
					<h3 class="mt-3 text-dark">Aliquam iaculis erat porta </h3>
					<p class="my-3">Nam ut nulla a ligula dictum imperdiet nec ligula dictum imperdiet nec</p>
					<a href="single.html">Read More</a>
				</div>
			</div>
		</div>
	</section>
	<!-- //about -->

	<!-- middle section -->
	<div class="w3ls-welcome py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="row">
				<div class="col-lg-5 welcome-right">
					<img src='{% static "home/images/b2.png" %}' alt=" " class="img-fluid">
				</div>
				<div class="col-lg-7 welcome-left mt-4">
					<h3>Awesome Theme for Medical and Health Websites</h3>
					<h6 class="mt-3">Suspendisse porta erat sit amet eros sagittis</h6>
					<h4 class="my-4 font-italic">Cum sociis natoque penatibus et magnis dis parturient montesmus, Proin vel nibh et
						elit mollis commodo et nec augue
						tristique sed.</h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse porta erat sit amet eros sagittis, quis
						hendrerit
						libero aliquam. Fusce semper augue ac dolor efficitur, a pretium metus pellentesque.</p>
					<div class="readmore-w3-agileits mt-md-5 mt-4">
						<a href="single.html" class="w3ls-button-agile text-dark">View Some More</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- //middle section -->

	<!-- team -->
	<section class="team py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="w3ls-titles text-center mb-5">
				<h3 class="title">Our Doctors</h3>
				<span>
					<i class="fas fa-user-md"></i>
				</span>
				<p class="mt-2">Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
			<div class="row inner-sec-w3layouts-agileinfo">
				<div class="col-md-4 team-grids text-center">
					<img src='{% static "home/images/t1.jpg"%}' class="img-fluid" alt="">
					<div class="team-info">
						<div class="caption">
							<h4>John Doe</h4>
							<h6>Doctor 1</h6>
						</div>
						<div class="social-icons-section">
							<a class="fac" href="#">
								<i class="fab fa-facebook"></i>
							</a>
							<a class="twitter" href="#">
								<i class="fab fa-twitter-square"></i>
							</a>
							<a class="pinterest" href="#">
								<i class="fab fa-pinterest"></i>
							</a>

						</div>

					</div>
				</div>
				<div class="col-md-4 team-grids my-md-0 my-4 text-center">
					<img src='{% static "home/images/t3.jpg"%}' class="img-fluid" alt="">
					<div class="team-info">
						<div class="caption">
							<h4>Adam Lobster</h4>
							<h6>Doctor 2</h6>
						</div>
						<div class="social-icons-section">
							<a class="fac" href="#">
								<i class="fab fa-facebook"></i>
							</a>
							<a class="twitter" href="#">
								<i class="fab fa-twitter-square"></i>
							</a>
							<a class="pinterest" href="#">
								<i class="fab fa-pinterest"></i>
							</a>

						</div>
					</div>
				</div>
				<div class="col-md-4 team-grids text-center">
					<img src='{% static "home/images/t4.jpg"%}' class="img-fluid" alt="">
					<div class="team-info">
						<div class="caption">
							<h4>Christina </h4>
							<h6>Doctor 3</h6>
						</div>
						<div class="social-icons-section">
							<a class="fac" href="#">
								<i class="fab fa-facebook"></i>
							</a>
							<a class="twitter" href="#">
								<i class="fab fa-twitter-square"></i>
							</a>
							<a class="pinterest" href="#">
								<i class="fab fa-pinterest"></i>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- team -->

	<!-- banner bottom -->
	<div class="banner-bottom py-5">
		<div class="d-flex container py-xl-3 py-lg-3">
			<div class="banner-left-bottom-w3ls offset-lg-2 offset-md-1">
				<h6 class="text-white">Sed do eiusmod tempor</h6>
				<h3 class="text-white my-3">High professional doctors</h3>
				<p>all specialists have extensive practical experience and regularly training courses in educational centers of the
					world</p>
			</div>
			<div class="button">
				<a href="{% url 'home:about'%}" class="w3ls-button-agile">Read More
					<i class="fas fa-hand-point-right"></i>
				</a>
			</div>
		</div>
	</div>
	<!-- //banner bottom -->

	<!-- services -->
	<div class="why-choose-agile pt-5" id="services">
		<div class="container pt-xl-5 pt-lg-3">
			<div class="w3ls-titles text-center mb-5">
				<h3 class="title">Our Best Services</h3>
				<span>
					<i class="fas fa-user-md"></i>
				</span>
				<p class="mt-2">Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
			<div class="row why-choose-agile-grids-top">
				<div class="col-lg-4 agileits-w3layouts-grid">
					<div class="row wthree_agile_us">
						<div class="col-3 agile-why-text p-0 text-right">
							<div class="wthree_features_grid">
								<i class="fas fa-user-md"></i>
							</div>
						</div>
						<div class="col-9 agile-why-text-2">
							<h4 class="text-dark font-weight-bold mb-3">General health care</h4>
							<p>Lorem ipsum magna, vehicula ut porta ete.</p>
						</div>
					</div>
					<div class="row wthree_agile_us my-5">
						<div class="col-3 agile-why-text p-0 text-right">
							<div class="wthree_features_grid">
								<i class="fas fa-syringe"></i>
							</div>
						</div>
						<div class="col-9 agile-why-text-2">
							<h4 class="text-dark font-weight-bold mb-3">Dental services</h4>
							<p>Lorem ipsum magna, vehicula ut porta ete.</p>
						</div>
					</div>
					<div class="row wthree_agile_us">
						<div class="col-3 agile-why-text p-0 text-right">
							<div class="wthree_features_grid">
								<i class="fab fa-medrt"></i>
							</div>
						</div>
						<div class="col-9 agile-why-text-2">
							<h4 class="text-dark font-weight-bold mb-3">Medical Treatment</h4>
							<p>Lorem ipsum magna, vehicula ut porta ete.</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 agileits-w3layouts-grid img text-center">
					<img src='{% static "home/images/b3.png"%}' alt=" " class="img-fluid" />
				</div>
				<div class="col-lg-4 agileits-w3layouts-grid">
					<div class="row wthree_agile_us">
						<div class="col-9 agile-why-text-2">
							<h4 class="text-dark font-weight-bold mb-3">Cardiac Clinic</h4>
							<p>Lorem ipsum magna, vehicula ut porta ete.</p>
						</div>
						<div class="col-3 agile-why-text p-0">
							<div class="wthree_features_grid">
								<i class="fas fa-medkit"></i>
							</div>
						</div>
					</div>
					<div class="row wthree_agile_us my-5">
						<div class="col-9 agile-why-text-2">
							<h4 class="text-dark font-weight-bold mb-3">Orthopedics</h4>
							<p>Lorem ipsum magna, vehicula ut porta ete.</p>
						</div>
						<div class="col-3 agile-why-text p-0">
							<div class="wthree_features_grid">
								<i class="fas fa-wheelchair"></i>
							</div>
						</div>
					</div>
					<div class="row wthree_agile_us">
						<div class="col-9 agile-why-text-2">
							<h4 class="text-dark font-weight-bold mb-3">Laboratory</h4>
							<p>Lorem ipsum magna, vehicula ut porta ete.</p>
						</div>
						<div class="col-3 agile-why-text p-0">
							<div class="wthree_features_grid">
								<i class="fas fa-hospital"></i>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- //services -->

{% endblock %}

home/templates/home/appointment.html
{% extends 'home/home.html'%}
{% load static %}
{% block change%}

	<!-- banner 2 -->
	<div class="inner-banner-w3ls">
		<div class="container">

		</div>
		<!-- //banner 2 -->
	</div>
	<!-- page details -->
	<div class="breadcrumb-agile">
		<div aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="index.html">Home</a>
				</li>
				<li class="breadcrumb-item active" aria-current="page">Appointment</li>
			</ol>
		</div>
	</div>
	<!-- //page details -->

{% endblock %}

{% block body%}

	<!-- contact -->
	<div class="appointment py-5">
		<div class="py-xl-5 py-lg-3">
			<div class="w3ls-titles text-center mb-5">
				<h3 class="title">Appointment</h3>
				<span>
					<i class="fas fa-user-md"></i>
				</span>
				<p class="mt-2">Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
			<div class="d-flex">
				<div class="appoint-img">

				</div>
				<div class="contact-right-w3l appoint-form">
					<h5 class="title-w3 text-center mb-5">Fill your appointment form</h5>
					<form action="#" method="post">
						<div class="form-group">
							<label for="recipient-name" class="col-form-label">Your Name</label>
							<input type="text" class="form-control" placeholder="Your Name " name="Name" id="recipient-name" required="">
						</div>
						<div class="form-group">
							<label for="recipient-phone" class="col-form-label">Your Email</label>
							<input type="email" class="form-control" placeholder="Your Email" name="email" id="recipient-phone" required="">
						</div>
						<div class="form-group">
							<label for="datepicker" class="col-form-label">Select your doctor</label>
							<select required="" class="form-control">
								<option value="">Select your doctor</option>
								<option value="1">Anne Dan</option>
								<option value="2">Carol Una</option>
								<option value="3">Diana Sue</option>
								<option value="4">Irene Sally</option>
								<option value="4">Jane Mary</option>
							</select>
						</div>
						<div class="form-group">
							<label for="datepicker" class="col-form-label">Select appointment date</label>
							<input placeholder="Date" class="date form-control" id="datepicker" type="text" value="" onfocus="this.value = '';"
							    onblur="if (this.value == '') {this.value = '';}" required="" />
						</div>
						<div class="form-group">
							<label for="datepicker" class="col-form-label">Select appointment time</label>
							<select required="" class="form-control">
								<option value="">Select Time</option>
								<option value="1">08:00-8:30</option>
								<option value="2">08:30-9:00</option>
								<option value="3"> 09:00-9:30</option>
								<option value="4">09:30-10:00</option>
							</select>
						</div>
						<div class="form-group">
							<label for="datepicker" class="col-form-label">Select City</label>
							<select required="" class="form-control">
								<option value="">Select City</option>
								<option value="1">city1</option>
								<option value="2">city2</option>
								<option value="3"> city3</option>
								<option value="4">city4</option>
							</select>
						</div>
						<div class="form-group">
							<label for="datepicker" class="col-form-label">Select Speciality</label>
							<select required="" class="form-control">
								<option value="">Select Speciality</option>
								<option value="1">Dermatology</option>
								<option value="2">ENT</option>
								<option value="3"> Genaral Medicine</option>
								<option value="4">Nutritionist</option>
							</select>
						</div>
						<input type="submit" value="Book Appointment" class="btn_apt">
					</form>
				</div>
				<div class="clerafix"></div>
			</div>
		</div>
	</div>
	<!-- //contact -->

{% endblock %}

home/templates/home/contact.html
{% extends 'home/home.html'%}
{% load static %}
{% block change%}

	<!-- banner 2 -->
	<div class="inner-banner-w3ls">
		<div class="container">

		</div>
		<!-- //banner 2 -->
	</div>
	<!-- page details -->
{% endblock %}

{% block body%}

	<div class="breadcrumb-agile">
		<div aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="index.html">Home</a>
				</li>
				<li class="breadcrumb-item active" aria-current="page">Contact Us</li>
			</ol>
		</div>
	</div>
	<!-- //page details -->

	<!-- contact -->
	<div class="agileits-contact py-5">
		<div class="py-xl-5 py-lg-3">
			<div class="w3ls-titles text-center mb-5">
				<h3 class="title">Contact Us</h3>
				<span>
					<i class="fas fa-user-md"></i>
				</span>
				<p class="mt-2">Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
			<div class="d-flex">
				<div class="col-lg-5 w3_agileits-contact-left">
				</div>
				<div class="col-lg-7 contact-right-w3l">
					<h5 class="title-w3 text-center mb-5">Get In Touch</h5>
					<form action="#" method="post">
						<div class="d-flex space-d-flex">
							<div class="form-group grid-inputs">
								<input type="text" class="name form-control" name="First Name" placeholder="First Name" required="">
							</div>
							<div class="form-group grid-inputs">
								<input type="text" class="name form-control" name="Last Name" placeholder="Last Name" required="">
							</div>
						</div>
						<div class="form-group">
							<input type="email" class="name form-control" name="Email" placeholder="Email" required="">
						</div>
						<div class="form-group">
							<input type="text" class="name form-control" name="Subject" placeholder="Subject" required="">
						</div>

						<div class="form-group">
							<textarea placeholder="Your Message" required="" class="form-control"></textarea>
						</div>
						<div class="form-group">
							<input type="submit" value="Send Message">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- //contact -->

	<!--&lt;!&ndash; Map &ndash;&gt;-->
	<!--<div class="map">-->
		<!--<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3048.5130900428026!2d44.506621715459396!3d40.17539347939393!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x406abcf86e940951%3A0x87a1923d7df42367!2sBest+Western+Congress+Hotel!5e0!3m2!1sen!2sin!4v1509605601510"></iframe>-->
	<!--</div>-->
	<!--&lt;!&ndash; //Map &ndash;&gt;-->

{% endblock %}

home/templates/home/gallery.html
{% extends 'home/home.html'%}
{% load static %}
{% block change%}
	<!-- banner 2 -->
	<div class="inner-banner-w3ls">
		<div class="container">

		</div>
		<!-- //banner 2 -->
	</div>
	<!-- page details -->
	<div class="breadcrumb-agile">
		<div aria-label="breadcrumb">
			<ol class="breadcrumb">
				<li class="breadcrumb-item">
					<a href="{% url 'home:index'%}">Home</a>
				</li>
				<li class="breadcrumb-item active" aria-current="page">Gallery</li>
			</ol>
		</div>
	</div>
	<!-- //page details -->
{% endblock %}

{% block body%}
	<!-- gallery -->
	<div class="gallery py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="w3ls-titles text-center mb-5">
				<h3 class="title">Gallery</h3>
				<span>
					<i class="fas fa-user-md"></i>
				</span>
				<p class="mt-2">Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
			<section>
				<ul id="da-thumbs" class="da-thumbs">
					<li>
						<a href='{% static "home/images/g1.jpg"%}' rel="" class="b-link-stripe b-animate-go  thickbox" title="Medic">
							<img src='{% static "home/images/g1.jpg"%}' alt="" class="img-fluid" />
							<div>
								<h5>Medic</h5>
								<span>Sed ut perspiciatis unde omnis iste natus error sit</span>
							</div>
						</a>
					</li>
					<li>
						<a href='{% static "home/images/g2.jpg"%}' rel="" class="b-link-stripe b-animate-go  thickbox" title="Medic">
							<img src='{% static "home/images/g2.jpg"%}' alt="" class="img-fluid" />
							<div>
								<h5>Medic</h5>
								<span>Sed ut perspiciatis unde omnis iste natus error sit</span>
							</div>
						</a>
					</li>
					<li>
						<a href='{% static "home/images/g3.jpg"%}' rel="" class="b-link-stripe b-animate-go  thickbox" title="Medic">

							<img src='{% static "home/images/g3.jpg"%}' alt="" class="img-fluid" />
							<div>
								<h5>Medic</h5>
								<span>Sed ut perspiciatis unde omnis iste natus error sit</span>
							</div>
						</a>
					</li>
					<li>
						<a href='{% static "home/images/g4.jpg"%}' rel="" class="b-link-stripe b-animate-go  thickbox" title="Medic">

							<img src='{% static "home/images/g4.jpg"%}' alt="" class="img-fluid" />
							<div>
								<h5>Medic</h5>
								<span>Sed ut perspiciatis unde omnis iste natus error sit</span>
							</div>
						</a>
					</li>
					<li>
						<a href='{% static "home/images/g6.jpg"%}' rel="" class="b-link-stripe b-animate-go  thickbox" title="Medic">

							<img src='{% static "home/images/g6.jpg"%}' alt="" class="img-fluid" />
							<div>
								<h5>Medic</h5>
								<span>Sed ut perspiciatis unde omnis iste natus error sit</span>
							</div>
						</a>
					</li>
					<li>
						<a href='{% static "home/images/g9.jpg"%}' rel="" class="b-link-stripe b-animate-go  thickbox" title="Medic">

							<img src='{% static "home/images/g9.jpg"%}' alt="" class="img-fluid" />
							<div>
								<h5>Medic</h5>
								<span>Sed ut perspiciatis unde omnis iste natus error sit</span>
							</div>
						</a>
					</li>
					<li>
						<a href='{% static "home/images/g8.jpg"%}' rel="" class="b-link-stripe b-animate-go  thickbox" title="Medic">

							<img src='{% static "home/images/g8.jpg"%}' alt="" class="img-fluid" />
							<div>
								<h5>Medic</h5>
								<span>Sed ut perspiciatis unde omnis iste natus error sit</span>
							</div>
						</a>
					</li>
					<li>
						<a href='{% static "home/images/g7.jpg"%}' rel="" class="b-link-stripe b-animate-go  thickbox" title="Medic">

							<img src='{% static "home/images/g7.jpg"%}' alt="" class="img-fluid" />
							<div>
								<h5>Medic</h5>
								<span>Sed ut perspiciatis unde omnis iste natus error sit</span>
							</div>
						</a>
					</li>
					<li>
						<a href='{% static "home/images/g5.jpg"%}' rel="" class="b-link-stripe b-animate-go  thickbox" title="Medic">

							<img src='{% static "home/images/g5.jpg"%}' alt="" class="img-fluid" />
							<div>
								<h5>Medic</h5>
								<span>Sed ut perspiciatis unde omnis iste natus error sit</span>
							</div>
						</a>
					</li>
				</ul>
			</section>
		</div>
	</div>
	<!-- //gallery -->

{% endblock %}